# Generated by Django 5.0.2 on 2024-02-19 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PetNeedDayCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('vaccination_status', models.BooleanField(default=False)),
                ('pet_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.petbreed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.pettype')),
            ],
        ),
        migrations.CreateModel(
            name='PetMeetUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('available_for_meet_up', models.BooleanField(default=False)),
                ('need_meet_up', models.BooleanField(default=False)),
                ('need_day_care', models.BooleanField(default=False)),
                ('pet_description', models.TextField()),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('coat_length', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('good_with', models.CharField(blank=True, max_length=50, null=True)),
                ('care_and_behavior', models.TextField(blank=True, null=True)),
                ('days_of_pet_finder', models.PositiveIntegerField(blank=True, null=True)),
                ('shelter_or_rescue', models.CharField(blank=True, max_length=100, null=True)),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('pet_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.petbreed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.pettype')),
            ],
        ),
        migrations.AddField(
            model_name='petbreed',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.pettype'),
        ),
        migrations.CreateModel(
            name='PetAvailableForDayCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.petbreed')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.pettype')),
            ],
        ),
    ]
