# Generated by Django 5.0.2 on 2024-02-20 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PetNeedDayCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('vaccination_status', models.BooleanField(default=False)),
                ('pet_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.petbreed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.pettype')),
            ],
        ),
        migrations.CreateModel(
            name='PetMeetUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('available_for_meet_up', models.BooleanField(default=False)),
                ('need_meet_up', models.BooleanField(default=False)),
                ('need_day_care', models.BooleanField(default=False)),
                ('day_care_available', models.BooleanField(default=False)),
                ('pet_description', models.TextField()),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('coat_length', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('good_with', models.CharField(blank=True, max_length=50, null=True)),
                ('care_and_behavior', models.TextField(blank=True, null=True)),
                ('days_of_pet_finder', models.PositiveIntegerField(blank=True, null=True)),
                ('shelter_or_rescue', models.CharField(blank=True, max_length=100, null=True)),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('pet_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.petbreed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.pettype')),
            ],
        ),
        migrations.AddField(
            model_name='petbreed',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.pettype'),
        ),
        migrations.CreateModel(
            name='PetAvailableForDayCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.petbreed')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmeetup_app.pettype')),
            ],
        ),
    ]
