# Generated by Django 5.0.2 on 2024-02-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petmeetup_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petmeetup',
            old_name='available_for_meet',
            new_name='available_for_meet_up',
        ),
        migrations.RenameField(
            model_name='petmeetup',
            old_name='need_meet',
            new_name='need_meet_up',
        ),
    ]
