# Generated by Django 5.0.2 on 2024-02-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmeetup_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='proof_id_card_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petmeetup',
            name='breed_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='pet_certificates'),
        ),
    ]
