# Generated by Django 5.0.2 on 2024-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmeetup_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmeetup',
            name='day_care_available',
            field=models.BooleanField(default=False),
        ),
    ]
