# Generated by Django 5.0.2 on 2024-02-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petmeetup_app', '0006_delete_user_customuser_email_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
